### ISSUE TITLE
Wordwrap performance issue

### ISSUE THREAD

**Issue by Metehan** [bonecode/EditBone#148]
Hi, firstly thank you for sharing this great application for free. It's my favourite ide.

There is a performance issue on wordwrap function. It gets almost frozen when you activate wordwrap for big files. You can reproduce this issue by wordwrapping bootstrap.min.js 

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css

**Comment by bonecode** [comment]
I see, the scrolling with the very long line is now also slow. I need to do some profiling for this.

**Comment by bonecode** [comment]
This is my editor control issue, so I created issue here: https://github.com/bonecode/TBCEditor/issues/371 

But I keep this here also.

**Comment by bonecode** [comment]
Fixed in the next release v. 10.10.0.
