### ISSUE TITLE
Can't use EditBone 11.1.0 with Windows XP

### ISSUE THREAD

**Issue by nickW4** [bonecode/EditBone#150]
EditBone crashes immediately.

Error messages:

List index out of bounds (43)

Access violation at address 008FA34E in module 'EditBone.exe'. Read of address 00000054.

**Comment by bonecode** [comment]
Whoa, who is still using Windows XP? I can't support that anymore. It's not even supported by Microsoft.

**Comment by nickW4** [comment]
Not fixed (11.1.1).

**Comment by bonecode** [comment]
Did you update highlighters?

**Comment by nickW4** [comment]
I downloaded EditBone32.zip, unpacked the archive in a new folder and ... crash.

**Comment by bonecode** [comment]
I think the EditBone.ini is somehow corrupted. Check C:\Users\<user name>\AppData\Local\EditBone or what ever is it in XP. Try to find the EditBone.ini. Delete [FileTypes] and open the application.

**Comment by nickW4** [comment]
It's OK now.
Thanks a lot.

**Comment by bonecode** [comment]
There isn't such a file. I think version 11.1.0 did corrupt the INI file. My bad.

**Comment by nickW4** [comment]
Should I delete the .ini files ?

1/ in the C:\Documents and Settings\<user name>\Local Settings\Application Data\EditBone
2/ in the program folder

**Comment by bonecode** [comment]
You can delete or rename those, if there are some important settings.

**Comment by nickW4** [comment]
I renamed the two files, and now everything looks OK.
Thanks.
