### ISSUE TITLE
Tabulators not consistent (at least) on text file 

### ISSUE THREAD

**Issue by mWaltari** [bonecode/EditBone#156]
I would expect the tabulator always to go on same column on every line.

![editbone-tabulators](https://cloud.githubusercontent.com/assets/4082975/16574270/cbb239ac-4285-11e6-90b6-06cf707ce735.gif)

**Comment by bonecode** [comment]
Set Tabulator Columns options to Yes.

![image](https://cloud.githubusercontent.com/assets/11475177/16578093/52ca27e0-42a1-11e6-8890-7451b47caf60.png)

**Comment by mWaltari** [comment]
I've got the Columns set for Yes

![screenshot 2016-07-05 11 52 23](https://cloud.githubusercontent.com/assets/4082975/16579155/10ae4480-42a7-11e6-8add-732ffabd5983.png)

**Comment by bonecode** [comment]
Bug: Tabs to spaces causing this.

**Comment by bonecode** [comment]
Moved https://github.com/bonecode/TBCEditor/issues/415

**Comment by bonecode** [comment]
Fixed.
