### ISSUE TITLE
Fixed standard implementation of Ctrl+F Search with Selection 

### ISSUE THREAD

**Issue by delphioracle** [bonecode/EditBone#170]
function TEBDocument.ToggleSearch(AShowPanel: Boolean = False): Boolean;
var
  LTabSheet: TsTabSheet;
...................................................................................................................
    Result := LTabSheet.PanelSearch.Visible;

    if Result then
      if Assigned(LTabSheet.ComboBoxSearchText) then
        if LTabSheet.ComboBoxSearchText.CanFocus then 
+     begin
          LTabSheet.ComboBoxSearchText.SetFocus;
+       if LTabSheet.Editor.SelectionAvailable then 
+       begin
+         LTabSheet.ComboBoxSearchText.Text := LTabSheet.Editor.SelectedText;
+         ComboBoxSearchTextChange(NIL);
+         LTabSheet.ComboBoxSearchText.SelectAll;
+       end;
+     end;

**Comment by bonecode** [comment]
Fixed.
