### ISSUE TITLE
Fixed Ctrl+F Search with multi line Selection 

### ISSUE THREAD

**Issue by delphioracle** [bonecode/EditBone#171]
function TEBDocument.ToggleSearch(AShowPanel: Boolean = False): Boolean;

  procedure ReadSearchOptions(AEditor: TBCEditor);
.................................
var
  LTabSheet: TsTabSheet;
  LSaveSelectionFlag: boolean;
begin
.................................
    if Result then
      if Assigned(LTabSheet.ComboBoxSearchText) then
        if LTabSheet.ComboBoxSearchText.CanFocus then begin
          if LTabSheet.Editor.SelectionAvailable then begin
            LTabSheet.ComboBoxSearchText.Text := LTabSheet.Editor.SelectedText;
            LSaveSelectionFlag := (soSearchOnTyping in LTabSheet.Editor.Search.Options)
              and (Pos(BCEDITOR_LINEFEED, LTabSheet.ComboBoxSearchText.Text)>0);  // multi line selection
            if not LSaveSelectionFlag then
              ComboBoxSearchTextChange(NIL);
          end else
            LSaveSelectionFlag := false;
          if LSaveSelectionFlag then
            LTabSheet.Editor.Search.Options := LTabSheet.Editor.Search.Options - [soSearchOnTyping];
          try
            LTabSheet.ComboBoxSearchText.SetFocus;
          finally
            if LSaveSelectionFlag then
              LTabSheet.Editor.Search.Options := LTabSheet.Editor.Search.Options + [soSearchOnTyping];
          end;
        end;
  end;
end;

**Comment by bonecode** [comment]
What you're trying to solve? Does not look a good solution.

**Comment by delphioracle** [comment]
I'm trying to save Selection after Ctrl+F. This standard behavior for RAD Studio, MS Word editors.
There are no bases to clean the Selection.
It is necessary for the user in the following cases:

1. Search in the Selection only.
2. Selection content view can be useful while searching and after Search completion.

**Comment by bonecode** [comment]
Well, in my RAD Studio Berlin selection only option does clean the selection. It does not work like I want it to work.

I fixed this, now if the selection only option is set, it will search only inside selection and will also highlight over selection. I still need to fix the case when nothing is found.

**Comment by bonecode** [comment]
I close this and create a new issue.
