### ISSUE TITLE
Missing TypeScript support

### ISSUE THREAD

**Issue by Zethalion** [bonecode/EditBone#176]
Hello, I have no idea if you already thought of this.

TypeScript compiles into plain JavaScript. It is a much easier language to handle complex projects. See http://www.typescriptlang.org/

I'd like to see TS support since I like the GUI over the other editors that support TS at the moment.

**Comment by bonecode** [comment]
Added the first version. I am not an expert of TypeScript. So, I just made a starting point for the highlighter.

**Comment by Zethalion** [comment]
Thanks!
