### ISSUE TITLE
Closing inactive tab with middle click does not check which tab was clicked on

### ISSUE THREAD

**Issue by mWaltari** [bonecode/EditBone#177]
It'll close always the Active tab instead of the Tab clicked. 

![closingtabswithmiddleclick](https://cloud.githubusercontent.com/assets/4082975/18777414/b05fbb26-8177-11e6-86a8-1a667ba174b3.gif)

**Comment by bonecode** [comment]
Keyword: MiddleClick

**Comment by bonecode** [comment]
Fixed.
