### ISSUE TITLE
LogFileUtils - Debugging facility of difficult programs - Fixed

### ISSUE THREAD

**Issue by delphioracle** [bonecode/EditBone#197]
[LogFileUtils.zip](https://github.com/bonecode/EditBone/files/746590/LogFileUtils.zip)

3 months ago I optimized EditBone in the Word Wrap mode (at the expense of an exception of excess calls of long procedures). Speed has increased >= twice. Now, when the source code for Word Wrap was stabilized and got rid of noticeable mistakes, I am going to execute final merge. For control and verification of difficult process of calls of procedures and the resources consumed by them the offered LogFileUtils will be used.

**Comment by bonecode** [comment]
Thanks, but logging is not my style of programming. And this project is so simple that it can be debugged and understood very easily.
